create table role (id int4 generated by default as identity, name varchar(255), primary key (id));
create table transcript (id int4 generated by default as identity, content text, end_time float4, start_time float4, video_id varchar(255), primary key (id));
create table user_account (id int4 generated by default as identity, active boolean not null, email varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id));
create table user_account_roles (users_id int4 not null, roles_id int4 not null, primary key (users_id, roles_id));
create table video (id varchar(255) not null, keyword varchar(255), lecturer varchar(255), status varchar(255), title varchar(255), upload_date timestamp, user_id int4, primary key (id));
alter table if exists transcript add constraint FKinftqujkp4uri62xvdyks3n9k foreign key (video_id) references video;
alter table if exists user_account_roles add constraint FKhgw1hs27q8latvqis3h4u9hh0 foreign key (roles_id) references role;
alter table if exists user_account_roles add constraint FK2yjg74yx0hqmuwkv3ltisijkn foreign key (users_id) references user_account;
alter table if exists video add constraint FKg8w0qnmcbnnrq5u2mm5569ays foreign key (user_id) references user_account;
